# Generated by Django 5.1.7 on 2025-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysLogininfor',
            fields=[
                ('info_id', models.BigAutoField(db_comment='访问ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, db_comment='用户账号', max_length=50, null=True)),
                ('ipaddr', models.CharField(blank=True, db_comment='登录IP地址', max_length=128, null=True)),
                ('login_location', models.CharField(blank=True, db_comment='登录地点', max_length=255, null=True)),
                ('browser', models.CharField(blank=True, db_comment='浏览器类型', max_length=50, null=True)),
                ('os', models.CharField(blank=True, db_comment='操作系统', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_comment='登录状态（0成功 1失败）', max_length=1, null=True)),
                ('msg', models.CharField(blank=True, db_comment='提示消息', max_length=255, null=True)),
                ('login_time', models.DateTimeField(blank=True, db_comment='访问时间', null=True)),
            ],
            options={
                'db_table': 'sys_logininfor',
                'db_table_comment': '系统访问记录',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysOperLog',
            fields=[
                ('oper_id', models.BigAutoField(db_comment='日志主键', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_comment='模块标题', max_length=50, null=True)),
                ('business_type', models.IntegerField(blank=True, db_comment='业务类型（0其它 1新增 2修改 3删除）', null=True)),
                ('method', models.CharField(blank=True, db_comment='方法名称', max_length=200, null=True)),
                ('request_method', models.CharField(blank=True, db_comment='请求方式', max_length=10, null=True)),
                ('operator_type', models.IntegerField(blank=True, db_comment='操作类别（0其它 1后台用户 2手机端用户）', null=True)),
                ('oper_name', models.CharField(blank=True, db_comment='操作人员', max_length=50, null=True)),
                ('dept_name', models.CharField(blank=True, db_comment='部门名称', max_length=50, null=True)),
                ('oper_url', models.CharField(blank=True, db_comment='请求URL', max_length=255, null=True)),
                ('oper_ip', models.CharField(blank=True, db_comment='主机地址', max_length=128, null=True)),
                ('oper_location', models.CharField(blank=True, db_comment='操作地点', max_length=255, null=True)),
                ('oper_param', models.CharField(blank=True, db_comment='请求参数', max_length=2000, null=True)),
                ('json_result', models.CharField(blank=True, db_comment='返回参数', max_length=2000, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='操作状态（0正常 1异常）', null=True)),
                ('error_msg', models.CharField(blank=True, db_comment='错误消息', max_length=2000, null=True)),
                ('oper_time', models.DateTimeField(blank=True, db_comment='操作时间', null=True)),
                ('cost_time', models.BigIntegerField(blank=True, db_comment='消耗时间', null=True)),
            ],
            options={
                'db_table': 'sys_oper_log',
                'db_table_comment': '操作日志记录',
                'managed': False,
            },
        ),
    ]
